
description: playbook-demo-junos

input:
  - playbook
  - inventory_file

output:
  - failed: <% ctx().failed %>
  - action_name: <% ctx().action_name %>

tasks:
  init:
    action: core.noop
    next:
    - publish:
        - failed: False
        - action_name: 'playbook-demo-junos'
      do: playbook

  playbook:
    action: ansible.playbook
    input:
      playbook: <% ctx().playbook %>
      inventory_file: <% ctx().inventory_file %>
    next:
      - when: <% succeeded() %>
        do: echo
        publish:
          - pb: <% result() %>
      - when: <% failed() %>
        do: echo
        publish:
          - failed: True
          - pb: <% result() %>
  
  echo:
    action: core.local
    input:
      cmd: echo <% ctx().pb %> 
    next:
      - do: post_msg
        publish:
          - msg: <% result() %>
  
  post_msg:
    action: slack.post_message
    input:
      message: <% ctx().msg %>
    next:
      - do: last
  
  last:
    action: core.noop
    next:
      - when: <% ctx().failed %>
        do: fail

