version: 1.0

description: playbook-demo

input:
  - playbook
  - inventory_file

output:
  - failed: <% ctx().failed %>
  - action_name: <% ctx().action_name %>

tasks:
  init:
    action: core.noop
    next:
    - publish:
        - failed: False
        - action_name: 'playbook-demo-junos'
      do: playbook

  playbook:
    action: ansible.playbook
    input:
      playbook: <% ctx().playbook %>
      inventory_file: <% ctx().inventory_file %>
    next:
      - when: <% succeeded() %>
        do: post_msg
        publish:
          - action_result: |-  
              [succeeded] <% result().succeeded %>
              [return_code] <% result().return_code %>
              [stdout] <% result().stdout %>
              [stderr] <% result().stderr %>
      - when: <% failed() %>
        do: post_msg
        publish:
          - failed: True
          - action_result: |-  
              [succeeded] <% result().succeeded %>
              [return_code] <% result().return_code %>
              [stdout] <% result().stdout %>
              [stderr] <% result().stderr %>
  
  
  post_msg:
    action: slack.post_message
    input:
      message: <% ctx().action_result %>
    next:
      - do: last
  
  last:
    action: core.noop
    next:
      - when: <% ctx().failed %>
        do: fail

